# production
server:
  host: 127.0.0.1
  port: 4000
  timezone: 'UTC'
  cluster: true

db:
  db: coke-oauth-twitter
  # optional, default: localhost
  host:
  # optional, default: 27017
  port: 27963
  # optional
  username:
  # optional
  password:

session:
  # optional, default: sessions
  collection:
  secret: 2e798a6d81f7235c10a93313dc222b5763a62ba6

logs:
  - error

libs: []

# libs that must run after server started
started: []
