# production
server:
  host: 127.0.0.1
  port: 4000
  timezone: 'UTC'
  cluster: true

db:
  db: APPNAME
  host: localhost
  # optional, default: 27017
  port : 27963
  # optional
  username :
  # optional
  password :
  # optional, default: sessions
  collection : sessions

logs:
  - error

libs: []

# libs that must run after server started
started: []
